FROM php:8.1-apache

RUN docker-php-ext-install mysqli pdo_mysql

COPY redlock-web-2.0.php /var/www/html/

RUN chown -R www-data:www-data /var/www/html

RUN chmod -R 755 /var/www/html

RUN find /var/www/html -type d -exec chmod g+s {} \;

EXPOSE 80